# 工作流名称
name: Build and Update Sing-box Rulesets

# 工作流触发条件
on:
  # 允许在 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:

  # 设置定时任务 (使用 CRON 表达式)
  schedule:
    # 这里的 '0 21 * * *' 代表 UTC 时间的晚上 21:00
    # 这对应北京时间 (UTC+8) 的第二天早上 5:00
    - cron: '0 21 * * *'
  
  # 当 main 分支有 push 事件时也触发 (可选)
  push:
    branches:
      - main
    paths:
      - '**.json'
      - '**.txt'

# 定义任务
jobs:
  build-rulesets:
    # 使用最新的 Ubuntu 虚拟机环境
    runs-on: ubuntu-latest

    # 定义任务中的各个步骤
    steps:
      # 步骤1：检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2：下载并设置 sing-box 编译工具
      - name: Download and setup sing-box
        run: |
          echo "Fetching the latest sing-box version..."
          LATEST_URL=$(curl -s "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | jq -r '.assets[] | .browser_download_url' | grep 'linux-amd64.tar.gz')
          echo "Downloading from: $LATEST_URL"
          wget -O sing-box.tar.gz "$LATEST_URL"
          tar -xzf sing-box.tar.gz
          mv sing-box-*/sing-box ./sing-box
          chmod +x ./sing-box
          echo "sing-box setup complete. Version:"
          ./sing-box version

      # 步骤3：创建用于存放临时规则文件的目录
      - name: Create temporary rule directories
        run: |
          mkdir -p ./rules/direct-ip
          mkdir -p ./rules/direct-domain

      # 步骤4：构建 direct-ip.srs
      - name: Build direct-ip.srs
        run: |
          echo "Building direct-ip.srs..."
          wget -P ./rules/direct-ip -i ./rule-list-ip.txt
          cp ./direct-ip.json ./rules/direct-ip/
          cd ./rules/direct-ip
          jq -s 'map(.rules) | add | { "version": 1, "rules": . }' *.json > entry-ip.json
          cd ../..
          echo "Compiling all IP rules from merged entry file..."
          ./sing-box rule-set compile ./rules/direct-ip/entry-ip.json -o direct-ip.srs
          echo "direct-ip.srs built successfully."

      # 步骤5：构建 direct-domain.srs
      - name: Build direct-domain.srs
        run: |
          echo "Building direct-domain.srs..."
          wget -P ./rules/direct-domain -i ./rule-list.txt
          cp ./direct-domain.json ./rules/direct-domain/
          cd ./rules/direct-domain
          jq -s 'map(.rules) | add | { "version": 1, "rules": . }' *.json > entry-domain.json
          cd ../..
          echo "Compiling all domain rules from merged entry file..."
          ./sing-box rule-set compile ./rules/direct-domain/entry-domain.json -o direct-domain.srs
          echo "direct-domain.srs built successfully."

      # 步骤6：构建 proxy rules
      - name: Build proxy rules
        run: |
          echo "Building proxy rules..."
          ./sing-box rule-set compile ./proxy-domain.json -o proxy-domain.srs
          echo "Proxy rules built successfully."

      # 步骤7：创建 Release 并上传规则文件
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # 使用日期和时间生成一个唯一的标签，例如 `ruleset-2025-09-27-09-30`
          tag_name: "ruleset-${{ env.RELEASE_DATE }}"
          # Release 的标题
          name: "Ruleset Build - ${{ env.RELEASE_DATE }}"
          # Release 的描述内容
          body: |
            这是由 GitHub Actions 自动构建的 Sing-box 规则集。
            包含以下文件：
            - direct-ip.srs
            - direct-domain.srs
            - proxy-domain.srs
          # 指定要上传的文件列表
          files: |
            direct-ip.srs
            direct-domain.srs
            proxy-domain.srs
        env:
          # 设置一个环境变量来存储当前的日期和时间
          RELEASE_DATE: $(date +'%Y-%m-%d-%H-%M')
          # GitHub Actions 会自动提供这个 token，用于授权
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
